# Generated by Django 4.2.6 on 2024-03-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='group',
        ),
        migrations.AddField(
            model_name='chat',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
